//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace smprojectMVC3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUsedTable
    {
        public int SerialNumber { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> LegoID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Type { get; set; }
        public Nullable<int> ProjectUsed { get; set; }
    
        public virtual LegoLibrary LegoLibrary { get; set; }
        public virtual SaveTable SaveTable { get; set; }
    }
}
