//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace smprojectMVC3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaveTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaveTable()
        {
            this.ProjectUsedTables = new HashSet<ProjectUsedTable>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectContent { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string MemberName { get; set; }
        public string Description { get; set; }
        public string ScreenShot { get; set; }
        public System.DateTime ProjectSaveTime { get; set; }
    
        public virtual MemberTable MemberTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectUsedTable> ProjectUsedTables { get; set; }
    }
}
